channels:
- conda-forge
dependencies:
- tensorflow>=2.0.0 # Must list before keras to preempt default keras backend
- h5py
- ipython
- matplotlib
- numpy
- opencv
- pims
- scipy
- scikit-image
- scikit-learn
- spyder
- tifffile
