channels:
- conda-forge
dependencies:
- python == 3.8
- future
- ipython
- tensorflow-gpu==2.4.1
- tensorflow-estimator==2.4.1
- opencv
- scikit-image
- scikit-learn
- matplotlib
- peakutils
- spyder
- caiman
